I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 104, in script
    $ syncActToGlobal()
  File "game/script.rpy", line 104, in <module>
    $ syncActToGlobal()
  File "game/core.rpy", line 23, in syncActToGlobal
    persistent.name = name_mod
NameError: global name 'name_mod' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 104, in script
    $ syncActToGlobal()
  File "renpy/ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 104, in <module>
    $ syncActToGlobal()
  File "game/core.rpy", line 23, in syncActToGlobal
    persistent.name = name_mod
NameError: global name 'name_mod' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.3.22090809
Doki Doki LifeTimes + 0.3
Sat Feb 22 13:53:33 2025
