I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 100, in script call
    call prologue from _call_prologue
  File "game/Prologue.rpy", line 35, in script
    show sayori turned happ afm at 11
TypeError: 'int' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 100, in script call
    call prologue from _call_prologue
  File "game/Prologue.rpy", line 35, in script
    show sayori turned happ afm at 11
  File "renpy/ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1378, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 698, in show
    img = i(img)
TypeError: 'int' object is not callable

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.3.22090809
Doki Doki LifeTimes Act 0 0.1
Sat Feb  1 13:25:51 2025
